# Configuration for actions/labeler

# Add 'documentation' label to any changes within 'docs/' or to markdown files
documentation:
  - changed-files:
      - any-glob-to-any-file:
        - 'docs/**'
        - '*.md'
        - 'mkdocs.yml'

# Add 'test' label to any changes within 'tests/'
test:
  - changed-files:
      - any-glob-to-any-file:
        - 'tests/**'
        - 'pytest.ini'

# Add 'ci' label to any changes within '.github/'
ci:
  - changed-files:
      - any-glob-to-any-file:
        - '.github/**'

# Add 'source' label to any changes within 'command_line_conflict/'
source:
  - changed-files:
      - any-glob-to-any-file:
        - 'command_line_conflict/**'

# Add 'dependencies' label to any changes to requirement files
dependencies:
  - changed-files:
      - any-glob-to-any-file:
        - 'requirements.txt'
        - 'pyproject.toml'
